version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/db
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8085:3000"
    postgres:
        image: postgres:latest
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: db
    # web:
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./web
    #         target: development
    #     command: npm run start
    #     volumes:
    #         - ./web:/sacha/web/src/app
    #         - /sacha/web/src/app/node_modules
    #     ports:
    #         - 4200:4200
    #     links:
    #         - api
